In [ ]:
from sklearn.datasets import load_wine
from datetime import timedelta
import pandas as pd
import numpy as np

In [ ]:
read_data_file = pd.read_pickle('../flink.pkl')
df = pd.DataFrame(read_data_file)

In [ ]:
df.columns

Index(['commit_befor ', 'commit_after', 'cal_smell', 'dispen_bf', 'object_bf',
       'bloater_bf', 'dispen_at', 'object_at', 'bloater_af', 'open_time',
       'closed_time', 'cal_time', 'changed_file', 'additions', 'deletions',
       'dev', 'cal_time_binaly'],
      dtype='object')

In [ ]:
df['cal_time'][0:20].median()

Timedelta('7 days 05:57:00')

In [ ]:
df['cal_time_binaly'] = df['cal_time'].apply(lambda x:  0 if x < timedelta (days = 7) else 1)

In [ ]:
#X = df[['commit_befor ', 'dispen_bf', 'object_bf', 'bloater_bf', 'open_time',]]
X = df[['commit_befor ', 'commit_after', 'cal_smell', 'dispen_bf', 'object_bf',
       'bloater_bf', 'dispen_at', 'object_at', 'bloater_af', 'open_time',
       'closed_time','changed_file', 'additions', 'deletions',
       'dev']]
y = df['cal_time_binaly']

In [ ]:
X = X.dropna()
y = y.dropna()

In [ ]:
X_train ,X_test ,y_train , y_test = X[:20], X[20:],y[:20],y[20:]

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto' , random_state = 2))

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.33333333, 0.66666667, 0.5       , 0.66666667, 0.33333333])

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [ ]:
confusion_matrix(y,y_pred)

array([[ 1, 11],
       [ 4, 14]], dtype=int64)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.56
recall_score =  0.7777777777777778
f1_score 0.6511627906976745


In [ ]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         18
y_pred    25
dtype: int64

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'gamma': ['scale', 'auto'],
                         'random_state': [2]},
             scoring='f1_macro')

In [ ]:
clf.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
clf.best_estimator_

SVC(C=1, random_state=2)

In [ ]:
y_pred = clf.predict(X)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
clf.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
clf.best_estimator_

SVC(C=1, random_state=2)

In [ ]:
y_pred_clf = clf.best_estimator_.predict(X)
y_pred_clf

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.3
recall_score =  0.5
f1_score 0.37499999999999994


C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#frame={"y":y,"y_pred_clf": y_pred_clf}
#pd.DataFrame(frame)

In [24]:
from matplotlib import pyplot as plt
from sklearn import svm
import numpy as np

def f_importances(coef, names):
    
    names = np.arange(1)
    imp = coef
    imp,names = zip(*sorted(zip(imp,names)))
    plt.barh(range(len(names)), imp, align='center')
    plt.yticks(range(len(names)), names)
    plt.show()

features_names = X.columns
svm1 = svm.SVC(kernel='linear',C=1)
svm1.fit(X, y)

In [ ]:
svm1.coef_

array([[ 2.02791707e-01,  3.40744616e-01,  1.37952909e-01,
         1.85611624e-01,  1.94632612e-01,  1.15714470e-01,
         1.82411774e-01, -1.05846384e-01,  3.90879273e-01,
        -3.86276367e-01,  1.12511262e-01,  7.77691502e-02,
        -5.35036114e-04,  4.69145889e-04,  7.72437431e-01]])

In [ ]:
import itertools
from itertools import product 

In [ ]:
result = itertools.combinations(X ,2)

for item in result:
    df  = pd.DataFrame(item)
    X[list (item)]
    parameters = {
    'C': [0.01 , 0.03 , 0.05 ],
    'gamma' : ['auto'],
    'random_state':[2]
    }
    svc = SVC()
    clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
    clf.fit(X_train[list (item)],y_train)
    clf.predict(X_test[list (item)])
    #print('predict=',clf.predict(X_test[list (item)]))
    #print(X_test)
    #print("y_train = ",y_train)
    print(item)
    print("precision_score =",precision_score(clf.predict(X[list(item)]),y))
    print("recall_score =", recall_score(clf.predict(X[list(item)]),y))
    print("f_1=",f1_score(clf.predict(X[list(item)]),y,average='macro'))
    #print("f_1_X-test=",f1_score(clf.predict(X_test[list(item)]),y_test,average='macro'))
    

('commit_befor ', 'commit_after')
precision_score = 0.5555555555555556
recall_score = 1.0
f_1= 0.7321428571428571
('commit_befor ', 'cal_smell')
precision_score = 0.5555555555555556
recall_score = 1.0
f_1= 0.7321428571428571
('commit_befor ', 'dispen_bf')
precision_score = 0.6666666666666666
recall_score = 1.0
f_1= 0.8
('commit_befor ', 'object_bf')
precision_score = 0.6111111111111112
recall_score = 0.8461538461538461
f_1= 0.699666295884316
('commit_befor ', 'bloater_bf')
precision_score = 0.7222222222222222
recall_score = 0.8125
f_1= 0.7285067873303168
('commit_befor ', 'dispen_at')
precision_score = 0.8333333333333334
recall_score = 0.8823529411764706
f_1= 0.8285714285714285
('commit_befor ', 'object_at')
precision_score = 0.6111111111111112
recall_score = 0.9166666666666666
f_1= 0.7333333333333334
('commit_befor ', 'bloater_af')
precision_score = 0.7777777777777778
recall_score = 0.7777777777777778
f_1= 0.7222222222222222
('commit_befor ', 'open_time')
precision_score = 0.777777777

In [ ]:
itertools.combinations_with_replacement(X,2)

In [ ]:
l = list(itertools.combinations(X,2))
print(l)

[('commit_befor ', 'commit_after'), ('commit_befor ', 'cal_smell'), ('commit_befor ', 'dispen_bf'), ('commit_befor ', 'object_bf'), ('commit_befor ', 'bloater_bf'), ('commit_befor ', 'dispen_at'), ('commit_befor ', 'object_at'), ('commit_befor ', 'bloater_af'), ('commit_befor ', 'open_time'), ('commit_befor ', 'closed_time'), ('commit_befor ', 'changed_file'), ('commit_befor ', 'additions'), ('commit_befor ', 'deletions'), ('commit_befor ', 'dev'), ('commit_after', 'cal_smell'), ('commit_after', 'dispen_bf'), ('commit_after', 'object_bf'), ('commit_after', 'bloater_bf'), ('commit_after', 'dispen_at'), ('commit_after', 'object_at'), ('commit_after', 'bloater_af'), ('commit_after', 'open_time'), ('commit_after', 'closed_time'), ('commit_after', 'changed_file'), ('commit_after', 'additions'), ('commit_after', 'deletions'), ('commit_after', 'dev'), ('cal_smell', 'dispen_bf'), ('cal_smell', 'object_bf'), ('cal_smell', 'bloater_bf'), ('cal_smell', 'dispen_at'), ('cal_smell', 'object_at'), ('

In [ ]:
print([''.join(i) for i in itertools.combinations(pd.DataFrame(X), 2)])

['commit_befor commit_after', 'commit_befor cal_smell', 'commit_befor dispen_bf', 'commit_befor object_bf', 'commit_befor bloater_bf', 'commit_befor dispen_at', 'commit_befor object_at', 'commit_befor bloater_af', 'commit_befor open_time', 'commit_befor closed_time', 'commit_befor changed_file', 'commit_befor additions', 'commit_befor deletions', 'commit_befor dev', 'commit_aftercal_smell', 'commit_afterdispen_bf', 'commit_afterobject_bf', 'commit_afterbloater_bf', 'commit_afterdispen_at', 'commit_afterobject_at', 'commit_afterbloater_af', 'commit_afteropen_time', 'commit_afterclosed_time', 'commit_afterchanged_file', 'commit_afteradditions', 'commit_afterdeletions', 'commit_afterdev', 'cal_smelldispen_bf', 'cal_smellobject_bf', 'cal_smellbloater_bf', 'cal_smelldispen_at', 'cal_smellobject_at', 'cal_smellbloater_af', 'cal_smellopen_time', 'cal_smellclosed_time', 'cal_smellchanged_file', 'cal_smelladditions', 'cal_smelldeletions', 'cal_smelldev', 'dispen_bfobject_bf', 'dispen_bfbloater_