**pandas data frames**

In [185]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [186]:
read_data_file = pd.read_csv('..\..\project_hive.csv')

In [187]:
df = pd.DataFrame(read_data_file)

In [188]:
df

url       commit    parents  \
0       https://github.com/apache/hive/commit/169e655    169e65592   bde6152    
1       https://github.com/apache/hive/commit/f7d2250     f7d2250a   ac6da6b    
2        https://github.com/apache/hive/commit/53f2c9     53f2c9e7   b94d111    
3     https://github.com/apache/hive/commit/2ef0b3855    2ef0b3855    909d0ee   
4      https://github.com/apache/hive/commit/99e59863     99e59863   5694c98    
5       https://github.com/apache/hive/commit/749e831      749e831   7968e1e    
6        https://github.com/apache/hive/commit/96083e    96083e717   d27fdcb    
7       https://github.com/apache/hive/commit/dcfc31b    dcfc31b83   30b40c4    
8      https://github.com/apache/hive/commit/2f9728ed    2f9728ed3   98a25f2    
9       https://github.com/apache/hive/commit/7ae6756     7ae6756d    8bcf7b9   
10      https://github.com/apache/hive/commit/216e73a      216e73a  216e73a7d   
11     https://github.com/apache/hive/commit/4377c7ff      4377c7f   ba864a2    
12     https://github.com/apache/hive/commit/d79c4595      d79c459    95dadac   
13     https://github.com/apache/hive/commit/dcc89501    dcc895016   4d03e31    
14    https://github.com/apache/hive/commit/18937bbe6  18937bbe645    bca4e89   
15     https://github.com/apache/hive/commit/53f2c9e7     53f2c9e7   b94d111    
16      https://github.com/apache/hive/commit/13814aa     13814aa4   f69fcce    
17      https://github.com/apache/hive/commit/a7baee7     a7baee7e    76c49b9   
18   https://github.com/apache/hive/commit/cf2158f6a4    cf2158f6a    0b01e5a   
19      https://github.com/apache/hive/commit/2f34486    2f3448686    008d7fa   
20    https://github.com/apache/hive/commit/138b662be      138b662   fa39cf2    
21     https://github.com/apache/hive/commit/169e6559     169e6559   bde6152    
22   https://github.com/apache/hive/commit/54dbd7fe2f     54dbd7fe    733aecf   
23   https://github.com/apache/hive/commit/102b23b16b      102b23b    00e0d55   
24     https://github.com/apache/hive/commit/2cabb8da      2cabb8d   163e0de    
25   https://github.com/apache/hive/commit/7cf7914729    7cf791472    20c95c1   
26  https://github.com/apache/hive/commit/edc53cc0d95    edc53cc0d    65f02d2   
27    https://github.com/apache/hive/commit/b0eb4151a    b0eb4151a    4af3a91   
28     https://github.com/apache/hive/commit/6ec140ed    6ec140ed2    a72db99   
29    https://github.com/apache/hive/commit/64af14458   64af144580    210c4dc   

    s106_before  s106_after  s112_before  s112_after  s125_before  s125_after  \
0             0           0            0           0            0           0   
1             0           0            0           0            0           0   
2             0           0            0           0            0           0   
3             0           0            2           0            2           3   
4             0           0            0           0            0           0   
5             0           0            0           0            0           0   
6             0           0            0           0            0           0   
7             0           0            0           0            0           0   
8             0           0            0           0            0           0   
9             0           0            0           0            0           0   
10            0           0            0           0            0           0   
11            0           0            0           0            0           0   
12            0           0            0           0            0           0   
13            0           0            0           0            0           0   
14            0           0            0           0            0           0   
15            0           0            0           0            0           0   
16            0           0            0           0            0           0   
17            0           0            0           0            0           0   

part of smell

In [189]:
commit_befor_sm = df.filter(regex='_befor')

In [190]:
commit_after_sm = df.filter(regex='_after')

In [191]:
group_befor_sm = df.filter(regex='_bf')

In [192]:
group_after_sm = df.filter(regex='_at')

In [193]:
#commit_after_sm.sum(axis=1)

In [194]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [195]:
commit_after = df['commit_after']

In [196]:
#commit_befor_sm.sum(axis=1)

In [197]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [198]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [199]:
commit_befor = df['commit_befor']

In [200]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [201]:
cal_smell =  df['cal_smell']

columns list

In [202]:
#list(df.columns)

In [203]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before' , 's2093_before' , 's1134_before' , 
            's1116_before' , 's1854_before' , 's3626_before']] 

In [204]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after' , 's2093_after' , 's1134_after' ,
            's1116_after' ,  's1854_after' , 's3626_after']] 

In [205]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before' , 's2986_before' , 's3358_before' ,
            's135_before' , 's1117_before' , 's1197_before' , 's1104_before' ,
            's5803_before' , 's1124_before' ]] 

In [206]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' , 's2986_after' , 's3358_after' ,
            's135_after' , 's1117_after' , 's1197_after' , 's1104_after' ,
            's5803_after' , 's1124_after']] 

In [207]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' , 
            's1066_before']] 

In [208]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            's1066_after']] 

In [209]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [210]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [211]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [212]:
data_time = df[{'open_time' , 'closed_time' }]

In [213]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [214]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [215]:
cal_time = df['cla_time']

In [216]:
cal_time.median()

Timedelta('16 days 17:18:00')

Information issus on GitHub 

In [217]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [218]:
changed_file = df['changed_file']

In [219]:
additions = df['additions']

In [220]:
deletions = df['deletions']

In [221]:
Dev = df['Dev']

data frame containing information 

In [222]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev 
                            })

In [223]:
from datetime import timedelta

In [224]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [225]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x < timedelta (days = 16) else 1)

In [226]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [227]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

In [228]:
pd.to_pickle(data_flink , './hive.pkl')

In [245]:
X

commit_befor   dispen_bf  object_bf  bloater_bf  open_time
0              12          0          0           3          2
1               3          0          1           2          1
2               3          1          2           0          5
3              29          3          2          22          1
4              26          0          0          26          8
5               7          5          1           1          4
6               4          0          4           0          3
7              14          0          1          13          6
8               2          0          1           1         12
9               0          0          0           0         10
10              5          5          0           0          4
11             13          0          0          13          4
12              0          0          0           0         11
13              4          0          4           0          1
14              0          0          0           0          1
15              6          6          0           0          5
16              0          0          0           0         10
17              0          0          0           0          7
18              8          6          1           1          5
19             11          0          0          11          1
20              2          1          1           0          1
21              7          1          0           6          2
22              1          1          0           0          3
23              0          0          0           0          3
24              2          2          0           0          7
25             11          0          0          11          6
26             92          0          0          91          7
27            136          0          0         136          4
28              0          0          0           0         10
29              0          0          0           0          2

Model

In [229]:
df_drop_nan = data_flink.dropna()

In [230]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [231]:
X ,y = df_drop_nan.iloc[:, [ True , False,  False , True , True ,True , False , False , False ,True , False , False, False , False , False , False,False]] , df_drop_nan['cal_time_binaly']

In [232]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [233]:
from sklearn.model_selection import cross_val_score

In [234]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.5       , 0.5       , 0.33333333, 0.5       , 0.66666667])

In [235]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1], dtype=int64)

In [236]:
from sklearn.metrics import confusion_matrix

In [237]:
confusion_matrix(y,y_pred)

array([[ 3, 11],
       [ 4, 12]], dtype=int64)

In [238]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.5217391304347826
recall_score =  0.75
f1_score 0.6153846153846153


In [239]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         16
y_pred    23
dtype: int64

In [240]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'degree': [1,2,4,8],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'degree': [1, 2, 4, 8],
                         'gamma': ['scale', 'auto'], 'random_state': [2]},
             scoring='f1_macro')

In [241]:
clf.best_estimator_

SVC(C=1, degree=1, random_state=2)

In [242]:
clf.best_score_

0.45955433455433453

In [243]:
y_pred_clf = clf.best_estimator_.predict(X)

In [244]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.8076923076923077
recall_score =  0.6428571428571428
f1_score 0.6031746031746033
