**pandas data frames**

In [1]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [2]:
read_data_file = pd.read_csv('..\..\project_hive.csv')

In [3]:
df = pd.DataFrame(read_data_file)

part of smell

In [4]:
commit_befor_sm = df.filter(regex='_befor')

In [5]:
commit_after_sm = df.filter(regex='_after')

In [6]:
group_befor_sm = df.filter(regex='_bf')

In [7]:
group_after_sm = df.filter(regex='_at')

In [8]:
#commit_after_sm.sum(axis=1)

In [9]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [10]:
commit_after = df['commit_after']

In [11]:
#commit_befor_sm.sum(axis=1)

In [12]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [13]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [14]:
commit_befor = df['commit_befor']

In [15]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [16]:
cal_smell =  df['cal_smell']

columns list

In [17]:
#list(df.columns)

In [18]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before' , 's2093_before' , 's1134_before' , 
            's1116_before' , 's1854_before' , 's3626_before']] 

In [19]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after' , 's2093_after' , 's1134_after' ,
            's1116_after' ,  's1854_after' , 's3626_after']] 

In [20]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before' , 's2986_before' , 's3358_before' ,
            's135_before' , 's1117_before' , 's1197_before' , 's1104_before' ,
            's5803_before' , 's1124_before' ]] 

In [21]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' , 's2986_after' , 's3358_after' ,
            's135_after' , 's1117_after' , 's1197_after' , 's1104_after' ,
            's5803_after' , 's1124_after']] 

In [22]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' , 
            's1066_before']] 

In [23]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            's1066_after']] 

In [24]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [25]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [26]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [27]:
data_time = df[{'open_time' , 'closed_time' }]

In [28]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [29]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [30]:
cal_time = df['cla_time']

In [31]:
cal_time.median()

Timedelta('16 days 17:18:00')

Information issus on GitHub 

In [32]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [33]:
changed_file = df['changed_file']

In [34]:
additions = df['additions']

In [35]:
deletions = df['deletions']

In [36]:
Dev = df['Dev']

data frame containing information 

In [37]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev 
                            })

In [38]:
from datetime import timedelta

In [39]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [40]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x < timedelta (days = 16) else 1)

In [41]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [42]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [43]:
df_drop_nan = data_flink.dropna()

In [44]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [45]:
X ,y = df_drop_nan.iloc[:, [ True , False,  False , True , True ,True , False , False , False ,True , False , False, False , False , False , False,False]] , df_drop_nan['cal_time_binaly']

In [46]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [47]:
from sklearn.model_selection import cross_val_score

In [48]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.5       , 0.5       , 0.33333333, 0.5       , 0.66666667])

In [49]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1], dtype=int64)

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y,y_pred)

array([[ 3, 11],
       [ 4, 12]], dtype=int64)

In [52]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.5217391304347826
recall_score =  0.75
f1_score 0.6153846153846153


In [53]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         16
y_pred    23
dtype: int64

In [54]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'degree': [1,2,4,8],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'degree': [1, 2, 4, 8],
                         'gamma': ['scale', 'auto'], 'random_state': [2]},
             scoring='f1_macro')

In [55]:
clf.best_estimator_

SVC(C=1, degree=1, random_state=2)

In [56]:
clf.best_score_

0.45955433455433453

In [57]:
y_pred_clf = clf.best_estimator_.predict(X)

In [58]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.8076923076923077
recall_score =  0.6428571428571428
f1_score 0.6031746031746033
