**pandas data frames**

In [193]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [194]:
read_data_file = pd.read_csv('..\..\project_hive.csv')

In [195]:
df = pd.DataFrame(read_data_file)

part of smell

In [196]:
commit_befor_sm = df.filter(regex='_befor')

In [197]:
commit_after_sm = df.filter(regex='_after')

In [198]:
group_befor_sm = df.filter(regex='_bf')

In [199]:
group_after_sm = df.filter(regex='_at')

In [200]:
#commit_after_sm.sum(axis=1)

In [201]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [202]:
commit_after = df['commit_after']

In [203]:
#commit_befor_sm.sum(axis=1)

In [204]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [205]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [206]:
commit_befor = df['commit_befor']

In [207]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [208]:
cal_smell =  df['cal_smell']

columns list

In [209]:
#list(df.columns)

In [210]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before' , 's2093_before' , 's1134_before' , 
            's1116_before' , 's1854_before' , 's3626_before']] 

In [211]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after' , 's2093_after' , 's1134_after' ,
            's1116_after' ,  's1854_after' , 's3626_after']] 

In [212]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before' , 's2986_before' , 's3358_before' ,
            's135_before' , 's1117_before' , 's1197_before' , 's1104_before' ,
            's5803_before' , 's1124_before' ]] 

In [213]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' , 's2986_after' , 's3358_after' ,
            's135_after' , 's1117_after' , 's1197_after' , 's1104_after' ,
            's5803_after' , 's1124_after']] 

In [214]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' , 
            's1066_before']] 

In [215]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            's1066_after']] 

In [216]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [217]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [218]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [219]:
data_time = df[{'open_time' , 'closed_time' }]

In [220]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [221]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [222]:
cal_time = df['cla_time']

In [223]:
cal_time.median()

Timedelta('16 days 17:18:00')

Information issus on GitHub 

In [224]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [225]:
changed_file = df['changed_file']

In [226]:
additions = df['additions']

In [227]:
deletions = df['deletions']

In [228]:
Dev = df['Dev']

data frame containing information 

In [229]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev 
                            })

In [230]:
from datetime import timedelta

In [231]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [232]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x > timedelta (days = 16) else 1)

In [233]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [234]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [235]:
df_drop_nan = data_flink.dropna()

In [236]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [254]:
X ,y = df_drop_nan.iloc[:, [ True , False,  False , True , True ,True , False , False , False ,True , False , False, False , False , False , False,False]] , df_drop_nan['cal_time_binaly']

In [255]:
y

0     0
1     0
2     0
3     1
4     1
5     0
6     1
7     0
8     1
9     0
10    0
11    1
12    1
13    0
14    1
15    1
16    0
17    1
18    1
19    1
20    0
21    0
22    0
23    0
24    1
25    0
26    1
27    1
28    0
29    0
Name: cal_time_binaly, dtype: int64

In [238]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators= 100 , random_state = 5)

In [239]:
from sklearn.model_selection import cross_val_score

In [240]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.66666667, 0.66666667, 0.33333333, 0.5       , 0.5       ])

In [241]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1], dtype=int64)

In [242]:
from sklearn.metrics import confusion_matrix

In [243]:
confusion_matrix(y,y_pred)

array([[12,  4],
       [10,  4]], dtype=int64)

In [244]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.5
recall_score =  0.2857142857142857
f1_score 0.36363636363636365


In [245]:
#print(pd.DataFrame(y , y_pred))

In [246]:
from sklearn.model_selection import GridSearchCV

parameters = {

    'max_depth' : [0.1,0.01,0.001],
    'min_impurity_decrease' : [0.1,0.01] ,
    'random_state':[0.1,1,2]
  
}
RandomForest = RandomForestClassifier()
clf = GridSearchCV(RandomForest, parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 355, in fit
    random_state = check_random_state(self.random_state)
  File "C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 886, in check_random_state
    raise ValueError('%r cannot be used to seed a numpy.random.RandomState'
ValueError: 0.1 cannot be used to seed a numpy.random.RandomState instance

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: Fi

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [0.1, 0.01, 0.001],
                         'min_impurity_decrease': [0.1, 0.01],
                         'random_state': [0.1, 1, 2]},
             scoring='f1_macro')

In [247]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_max_depth',
 'param_min_impurity_decrease',
 'param_random_state',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [248]:
clf.best_estimator_

RandomForestClassifier(max_depth=0.1, min_impurity_decrease=0.1, random_state=2)

In [249]:
clf.best_score_

0.34722222222222215

In [250]:
y_pred = cross_val_predict(clf.best_estimator_,X,y)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [251]:
y_pred_clf = clf.best_estimator_.predict(X)

In [252]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.26666666666666666
recall_score =  0.5
f1_score 0.3478260869565218


C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
