**pandas data frames**

In [56]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [57]:
read_data_file = pd.read_csv('project_hive.csv')

In [58]:
df = pd.DataFrame(read_data_file)

part of smell

In [59]:
commit_befor_sm = df.filter(regex='_befor')

In [60]:
commit_after_sm = df.filter(regex='_after')

In [61]:
group_befor_sm = df.filter(regex='_bf')

In [62]:
group_after_sm = df.filter(regex='_at')

In [63]:
#commit_after_sm.sum(axis=1)

In [64]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [65]:
commit_after = df['commit_after']

In [66]:
#commit_befor_sm.sum(axis=1)

In [67]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [68]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [69]:
commit_befor = df['commit_befor']

In [70]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [71]:
cal_smell =  df['cal_smell']

columns list

In [72]:
#list(df.columns)

In [73]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before' , 's2093_before' , 's1134_before' , 
            's1116_before' , 's1854_before' , 's3626_before']] 

In [74]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after' , 's2093_after' , 's1134_after' ,
            's1116_after' ,  's1854_after' , 's3626_after']] 

In [75]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before' , 's2986_before' , 's3358_before' ,
            's135_before' , 's1117_before' , 's1197_before' , 's1104_before' ,
            's5803_before' , 's1124_before' ]] 

In [76]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' , 's2986_after' , 's3358_after' ,
            's135_after' , 's1117_after' , 's1197_after' , 's1104_after' ,
            's5803_after' , 's1124_after']] 

In [77]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' , 
            's1066_before']] 

In [78]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            's1066_after']] 

In [79]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [80]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [81]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [82]:
data_time = df[{'open_time' , 'closed_time' }]

In [83]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [84]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [85]:
cal_time = df['cla_time']

In [86]:
cal_time.median()

Timedelta('16 days 17:18:00')

Information issus on GitHub 

In [87]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [88]:
changed_file = df['changed_file']

In [89]:
additions = df['additions']

In [90]:
deletions = df['deletions']

In [91]:
Dev = df['Dev']

data frame containing information 

In [92]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev ,
                              
                            })

In [93]:
from datetime import timedelta

In [94]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [95]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x > timedelta (days = 16) else 1)

In [96]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [97]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [98]:
df_drop_nan = data_flink.dropna()

In [99]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [100]:
X ,y = df_drop_nan.iloc[:, [ True , True,  True , True , True ,True , True , True , True ,True , True , False, True , True , True , True ,False]] , df_drop_nan['cal_time_binaly']

In [101]:
from sklearn.ensemble import GradientBoostingClassifier
X_train, X_test = X[:30], X[30:]
y_train, y_test = y[:30], y[30:]
clf = GradientBoostingClassifier(n_estimators= 100, learning_rate= 1.0 , max_depth = 1 , random_state=0).fit(X_train , y_train)

In [102]:
from sklearn.model_selection import cross_val_score

In [103]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.66666667, 0.33333333, 0.66666667, 0.33333333, 0.66666667])

In [104]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0], dtype=int64)

In [105]:
from sklearn.metrics import confusion_matrix

In [106]:
confusion_matrix(y , y_pred)

array([[9, 7],
       [7, 7]], dtype=int64)

In [107]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred ))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred ))

precision =  0.5
recall_score =  0.5
f1_score 0.5
