**pandas data frames**

In [100]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [101]:
read_data_file = pd.read_csv('type_smells.csv')

In [102]:
df = pd.DataFrame(read_data_file)

In [103]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

In [104]:
dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

part of smell

In [105]:
commit_befor_sm = df.filter(regex='_befor')

In [106]:
commit_after_sm = df.filter(regex='_after')

In [107]:
group_befor_sm = df.filter(regex='_bf')

In [108]:
group_after_sm = df.filter(regex='_at')

In [109]:
commit_after_sm.sum(axis=1)

0      6
1     12
2      9
3      5
4      7
5      2
6     18
7      4
8      2
9      4
10     4
11     2
12     1
13    26
14     7
15    14
16    21
17     2
18    11
19    32
20     3
21    12
22    10
23     6
24     7
25    12
26     4
27     2
28     1
29     5
dtype: int64

In [110]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [111]:
commit_after = df['commit_after']

In [112]:
commit_befor_sm.sum(axis=1)

0      9
1     11
2      9
3     18
4      4
5     12
6      3
7      7
8      6
9      3
10    11
11    12
12    22
13     1
14     7
15    12
16    29
17     1
18     2
19    44
20    12
21     2
22     6
23    10
24     7
25     2
26     8
27     8
28    12
29    24
dtype: int64

In [113]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [114]:
commit_befor = df['commit_befor']

In [115]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [116]:
cal_smell =  df['cal_smell']

columns list

In [117]:
list(df.columns)

['url',
 'commit',
 'parents',
 's106_before',
 's106_after',
 's112_before',
 's112_after',
 's119_before',
 's119_after',
 's1123_before',
 's1123_after',
 's1133_before',
 's1133_after',
 's1141_before',
 's1141_after',
 's1155_before',
 's1155_after',
 's1168_before',
 's1168_after',
 's1172_before',
 's1172_after',
 's1181_before',
 's1181_after',
 's1187_before',
 's1187_after',
 's1192_before',
 's1192_after',
 's1199_before',
 's1199_after',
 's1610_before',
 's1610_after',
 's1612_before',
 'S1612_after',
 's1643_before',
 's1643_after',
 's1874_before',
 's1874_after',
 's1948_before',
 's1948_after',
 's1199_before.1',
 's1199_after.1',
 's2139_before',
 's2139_after',
 's2699_before',
 's2699_after',
 's2293_before',
 's2293_after',
 's3011_before',
 's3011_after',
 's3400_before',
 's3400_after',
 's3415_before',
 's3415_after',
 's3358_before',
 's3358_after',
 's3740_before',
 's3740_after',
 's3776_before',
 's3776_after',
 's4042_before',
 's4042_after',
 's5411_before

Set data type time  

In [118]:
data_time = df[{'open_time' , 'closed_time' }]

In [119]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [120]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [121]:
cal_time = df['cla_time']

In [74]:
cal_time.median()

Timedelta('17 days 02:22:30')

Information issus on GitHub 

In [75]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [76]:
changed_file = df['changed_file']

In [77]:
additions = df['additions']

In [78]:
deletions = df['deletions']

In [79]:
Dev = df['Dev']

data frame containing information 

In [80]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev ,
                              
                            })

In [81]:
from datetime import timedelta

In [82]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [83]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x > timedelta (days = 17) else 1)

In [84]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [85]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [86]:
df_drop_nan = data_flink.dropna()

In [87]:
from sklearn.datasets import load_wine
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np

In [88]:
X ,y = df_drop_nan.iloc[:, [ True , True,  True , True , True ,True , True , True , True ,True , True , False, True , True , True , True ,False]] , df_drop_nan['cal_time_binaly']

In [89]:
from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier(n_estimators= 100 , random_state = 5)


In [90]:
from sklearn.model_selection import cross_val_score

In [91]:
cross_val_score(forest_clf , X , y , cv=4 ,scoring= "accuracy")

array([0.625     , 0.28571429, 0.57142857, 0.28571429])

In [92]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(forest_clf,X,y,cv=3)
y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [93]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_hastie_10_2

#X, y = make_hastie_10_2(random_state=0)
X_train, X_test = X[:5], X[5:]
y_train, y_test = y[:5], y[5:]

clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(X_train, y_train)

In [94]:
cross_val_score(clf , X , y , cv=4 ,scoring= "accuracy")

array([0.5       , 0.42857143, 0.85714286, 0.42857143])

In [95]:
clf.score(X_test, y_test)

0.5416666666666666

In [122]:
y_pred = cross_val_predict(clf,X,y,cv=3)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [123]:
confusion_matrix(y,y_pred)

array([[ 6,  8],
       [ 4, 11]], dtype=int64)

In [124]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.5789473684210527
recall_score =  0.7333333333333333
f1_score 0.6470588235294117


In [98]:
y = y.reset_index(drop = True)

In [99]:
pd.concat([pd.DataFrame(y),pd.DataFrame(y_pred)] , axis=1)

cal_time_binaly  0
0                 0  1
1                 0  0
2                 0  1
3                 1  1
4                 1  1
5                 1  1
6                 1  0
7                 1  1
8                 1  1
9                 1  0
10                1  1
11                1  1
12                0  0
13                1  1
14                0  0
15                0  0
16                1  1
17                1  0
18                0  0
19                1  1
20                0  0
21                0  1
22                0  0
23                1  1
24                0  0
25                0  1
26                0  1
27                1  1
28                0  1