**pandas data frames**

In [126]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [127]:
read_data_file = pd.read_csv('..\..\project_flink.csv')

In [128]:
df = pd.DataFrame(read_data_file)

part of smell

In [129]:
commit_befor_sm = df.filter(regex='_befor')

In [130]:
commit_after_sm = df.filter(regex='_after')

In [131]:
group_befor_sm = df.filter(regex='_bf')

In [132]:
group_after_sm = df.filter(regex='_at')

In [133]:
#commit_after_sm.sum(axis=1)

In [134]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [135]:
commit_after = df['commit_after']

In [136]:
#commit_befor_sm.sum(axis=1)

In [137]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [138]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [139]:
commit_befor = df['commit_befor']

In [140]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [141]:
cal_smell =  df['cal_smell']

columns list

In [142]:
#list(df.columns)

In [143]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before'  
             ]] 

In [144]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after'  ]]

In [145]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before'  , 's3358_before' ,
             ]] 

In [146]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' ,  's3358_after' ,
            
            ]] 

In [147]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' ]] 

In [148]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after']] 

In [149]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [150]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [151]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [152]:
data_time = df[{'open_time' , 'closed_time' }]

In [153]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [154]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [155]:
cal_time = df['cla_time']

In [156]:
cal_time.median()

Timedelta('17 days 02:22:30')

Information issus on GitHub 

In [157]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [158]:
changed_file = df['changed_file']

In [159]:
additions = df['additions']

In [160]:
deletions = df['deletions']

In [161]:
Dev = df['Dev']

data frame containing information 

In [162]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev ,
                              
                            })

In [163]:
from datetime import timedelta

In [164]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [165]:
data_flink['cal_time'].median()

Timedelta('17 days 02:22:30')

In [166]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x > timedelta (days = 17) else 1)

In [167]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [168]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [169]:
df_drop_nan = data_flink.dropna()

In [170]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [171]:
X ,y = df_drop_nan.iloc[:, [ True , True,  True , True , True ,True , True , True , True ,True , True , False, True , True , True , True ,False]] , df_drop_nan['cal_time_binaly']

In [172]:
X

commit_befor   commit_after  cal_smell  dispen_bf  object_bf  bloater_bf  \
0               9             6         -3          2          6           0   
1              11            12          1          1          8           0   
2               9             9          0          0          7           0   
3              18             5        -13          3          4           0   
4               4             7          3          0          2           0   
5              12             2        -10          0         10           0   
6               3            18         15          0          0           0   
7               7             4         -3          0          0           0   
8               6             2         -4          0          0           0   
9               3             4          1          0          0           0   
10             11             4         -7          3          6           0   
11             12             2        -10          6          5           0   
12             22             1        -21         14          4           0   
13              1            26         25          0          0           0   
14              7             7          0          3          0           0   
15             12            14          2         10          0           0   
16             29            21         -8         16          0          10   
17              1             2          1          0          0           0   
18              2            11          9          1          0           0   
19             44            32        -12         41          2           1   
20             12             3         -9         10          0           0   
21              2            12         10          0          0           0   
22              6            10          4          2          0           0   
23             10             6         -4          1          5           2   
24              7             7          0          0          2           0   
25              2            12         10          0          0           0   
26              8             4         -4          4          1           0   
27              8             2         -6          7          0           0   
28             12             1        -11          4          7           0   
29             24             5        -19          4          5          14   

    dispen_at  object_at  bloater_af  open_time  closed_time  changed_file  \
0           5          0           0          9            8            45   
1           8          0           0          2            4            15   
2           4          0           3          9            1             9   
3           1          0           0          3            3             5   
4           3          3           0          7            7             9   
5           1          0           0          8            8            32   
6           0          0           0          4            4             8   
7           0          0           0         12           12            47   
8           0          0           0          2            2            34   
9           0          0           0         11           11             3   
10          0          0           0          6            6             7   
11          0          0           0          4            4            14   
12          0          0           0         11           11           257   
13         22          0           0          6            8            22   
14          1          3           0          9            9            15   
15          6          9           1         12            1           882   
16         16          9           0         11            1            89   
17          1          1           0          8            8             9   
18          9          9           0     

In [173]:
from sklearn.ensemble import GradientBoostingClassifier
X_train, X_test = X[:20], X[20:]
y_train, y_test = y[:20], y[20:]
clf = GradientBoostingClassifier(n_estimators=1, learning_rate=1.0 , max_depth=1 , random_state=2).fit(X_train , y_train)

In [174]:
from sklearn.model_selection import cross_val_score

In [175]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.66666667, 0.83333333, 1.        , 0.66666667, 0.33333333])

In [176]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [177]:
from sklearn.metrics import confusion_matrix

In [178]:
confusion_matrix(y , y_pred)

array([[ 8,  7],
       [ 2, 13]], dtype=int64)

In [179]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred ,average='macro'))
print('recall_score = ', recall_score(y,y_pred ,average='macro'))
print('f1_score',f1_score(y,y_pred ,average='macro'))


precision =  0.7250000000000001
recall_score =  0.7
f1_score 0.6914285714285715


In [180]:
#sorted(clf.cv_results_.keys())

In [181]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         15
y_pred    20
dtype: int64

In [182]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'learning_rate': [0.01 , 0.1 ,1],
    'n_estimators': [100,200,400,800],
    'subsample' : [0.5 , 1],
    'max_depth' : [1,2,4,8] ,
    'random_state':[2]
  
}
GradientBoosting = GradientBoostingClassifier()
clf = GridSearchCV(GradientBoosting, parameters , cv=3 , scoring='f1_macro')
clf.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 1],
                         'max_depth': [1, 2, 4, 8],
                         'n_estimators': [100, 200, 400, 800],
                         'random_state': [2], 'subsample': [0.5, 1]},
             scoring='f1_macro')

In [183]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_learning_rate',
 'param_max_depth',
 'param_n_estimators',
 'param_random_state',
 'param_subsample',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [184]:
clf.best_estimator_

GradientBoostingClassifier(learning_rate=0.01, max_depth=1, random_state=2,
                           subsample=1)

In [185]:
clf.best_score_

0.6788840788840789

In [186]:
y_pred = cross_val_predict(clf.best_estimator_,X_test,y_test)
y_pred

C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [187]:
y_pred_clf = clf.best_estimator_.predict(X_test)

In [188]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y_test,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y_test,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y_test,y_pred_clf ,average='macro'))

precision =  0.6875
recall_score =  0.6428571428571428
f1_score 0.4949494949494949
