**pandas data frames**

In [65]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [66]:
read_data_file = pd.read_csv('..\..\project_hive.csv')

In [67]:
df = pd.DataFrame(read_data_file)

part of smell

In [68]:
commit_befor_sm = df.filter(regex='_befor')

In [69]:
commit_after_sm = df.filter(regex='_after')

In [70]:
group_befor_sm = df.filter(regex='_bf')

In [71]:
group_after_sm = df.filter(regex='_at')

In [72]:
#commit_after_sm.sum(axis=1)

In [73]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [74]:
commit_after = df['commit_after']

In [75]:
#commit_befor_sm.sum(axis=1)

In [76]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [77]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [78]:
commit_befor = df['commit_befor']

In [79]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [80]:
cal_smell =  df['cal_smell']

columns list

In [81]:
#list(df.columns)

In [82]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before' , 's2093_before' , 's1134_before' , 
            's1116_before' , 's1854_before' , 's3626_before']] 

In [83]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after' , 's2093_after' , 's1134_after' ,
            's1116_after' ,  's1854_after' , 's3626_after']] 

In [84]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before' , 's2986_before' , 's3358_before' ,
            's135_before' , 's1117_before' , 's1197_before' , 's1104_before' ,
            's5803_before' , 's1124_before' ]] 

In [85]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' , 's2986_after' , 's3358_after' ,
            's135_after' , 's1117_after' , 's1197_after' , 's1104_after' ,
            's5803_after' , 's1124_after']] 

In [86]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' , 
            's1066_before']] 

In [87]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            's1066_after']] 

In [88]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [89]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [90]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [91]:
data_time = df[{'open_time' , 'closed_time' }]

In [92]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [93]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [94]:
cal_time = df['cla_time']

In [95]:
cal_time.median()

Timedelta('16 days 17:18:00')

Information issus on GitHub 

In [96]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [97]:
changed_file = df['changed_file']

In [98]:
additions = df['additions']

In [99]:
deletions = df['deletions']

In [100]:
Dev = df['Dev']

data frame containing information 

In [101]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev ,
                              
                            })

In [102]:
from datetime import timedelta

In [103]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [104]:
data_flink['cal_time'].median()

Timedelta('16 days 17:18:00')

In [105]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x < timedelta (days = 16) else 1)

In [106]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [107]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [108]:
df_drop_nan = data_flink.dropna()

In [109]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [110]:
X ,y = df_drop_nan.iloc[:, [ True , True,  True , True , True ,True , True , True , True ,True , True , False, True , True , True , True ,False]] , df_drop_nan['cal_time_binaly']

In [111]:
X

commit_befor   commit_after  cal_smell  dispen_bf  object_bf  bloater_bf  \
0            12.0           1.0      -11.0        0.0        0.0         3.0   
1             3.0           3.0        0.0        0.0        1.0         2.0   
2             3.0           0.0       -3.0        1.0        2.0         0.0   
3            29.0           3.0      -26.0        3.0        2.0        22.0   
4            26.0           2.0      -24.0        0.0        0.0        26.0   
5             7.0           1.0       -6.0        5.0        1.0         1.0   
6             4.0           0.0       -4.0        0.0        4.0         0.0   
7            14.0           0.0      -14.0        0.0        1.0        13.0   
8             2.0           1.0       -1.0        0.0        1.0         1.0   
9             0.0           2.0        2.0        0.0        0.0         0.0   
10            5.0           0.0       -5.0        5.0        0.0         0.0   
11           13.0           0.0      -13.0        0.0        0.0        13.0   
12            0.0          16.0       16.0        0.0        0.0         0.0   
13            4.0           2.0       -2.0        0.0        4.0         0.0   
14            0.0          20.0       20.0        0.0        0.0         0.0   
15            6.0          37.0       31.0        6.0        0.0         0.0   
16            0.0          52.0       52.0        0.0        0.0         0.0   
17            0.0           0.0        0.0        0.0        0.0         0.0   
18            8.0           0.0       -8.0        6.0        1.0         1.0   
19           11.0           0.0      -11.0        0.0        0.0        11.0   
20            2.0           0.0       -2.0        1.0        1.0         0.0   
21            7.0           0.0       -7.0        1.0        0.0         6.0   
22            1.0           2.0        1.0        1.0        0.0         0.0   
23            0.0          14.0       14.0        0.0        0.0         0.0   
24            2.0          15.0       13.0        2.0        0.0         0.0   
25           11.0          10.0       -1.0        0.0        0.0        11.0   
26           92.0           1.0      -91.0        0.0        0.0        91.0   
27          136.0           0.0     -136.0        0.0        0.0       136.0   
28            0.0           4.0        4.0        0.0        0.0         0.0   
29            0.0           2.0        2.0        0.0        0.0         0.0   

    dispen_at  object_at  bloater_af  open_time  closed_time  changed_file  \
0         0.0        0.0         1.0        2.0          5.0          25.0   
1         3.0        0.0         0.0        1.0         12.0          92.0   
2         0.0        0.0         0.0        5.0         12.0           6.0   
3         0.0        0.0         0.0        1.0          1.0          74.0   
4         0.0        0.0         1.0        8.0          9.0          63.0   
5         1.0        0.0         0.0        4.0         10.0           3.0   
6         0.0        0.0         0.0        3.0          3.0          40.0   
7         0.0        0.0         0.0        6.0          7.0          11.0   
8         1.0        0.0         0.0       12.0         12.0           7.0   
9         2.0        0.0         0.0       10.0         10.0         120.0   
10        0.0        0.0         0.0        4.0          5.0          11.0   
11        0.0        0.0         0.0        4.0          4.0           4.0   
12        0.0        0.0        16.0       11.0         12.0         124.0   
13        0.0        0.0         0.0        1.0         11.0           7.0   
14        0.0        0.0        20.0        1.0          1.0         288.0   
15        1.0        2.0        34.0        5.0          5.0           6.0   
16        0.0        0.0        52.0       10.0         10.0           2.0   
17        0.0        0.0         0.0        7.0          7.0          78.0   
18        0.0        0.0         0.0     

In [112]:
from sklearn.ensemble import GradientBoostingClassifier
X_train, X_test = X[:20], X[20:]
y_train, y_test = y[:20], y[20:]
clf = GradientBoostingClassifier(n_estimators=1, learning_rate=1.0 , max_depth=1 , random_state=2).fit(X_train , y_train)

In [113]:
from sklearn.model_selection import cross_val_score

In [114]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.83333333, 0.33333333, 0.5       , 0.5       , 0.66666667])

In [115]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [116]:
from sklearn.metrics import confusion_matrix

In [117]:
confusion_matrix(y , y_pred)

array([[ 3, 11],
       [ 2, 14]], dtype=int64)

In [118]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred ,average='macro'))
print('recall_score = ', recall_score(y,y_pred ,average='macro'))
print('f1_score',f1_score(y,y_pred ,average='macro'))


precision =  0.5800000000000001
recall_score =  0.5446428571428571
f1_score 0.4993581514762516


In [119]:
#sorted(clf.cv_results_.keys())

In [120]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         16
y_pred    25
dtype: int64

In [121]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'learning_rate': [0.01 , 0.1 ,1],
    'n_estimators': [1,2,4,8],
    'subsample' : [0.5 , 1],
    'max_depth' : [1,2,4,8] ,
    'random_state':[2]
  
}
GradientBoosting = GradientBoostingClassifier()
clf = GridSearchCV(GradientBoosting, parameters , cv=3 , scoring='f1_macro')
clf.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 1],
                         'max_depth': [1, 2, 4, 8],
                         'n_estimators': [1, 2, 4, 8], 'random_state': [2],
                         'subsample': [0.5, 1]},
             scoring='f1_macro')

In [122]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_learning_rate',
 'param_max_depth',
 'param_n_estimators',
 'param_random_state',
 'param_subsample',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [123]:
clf.best_estimator_

GradientBoostingClassifier(max_depth=1, n_estimators=8, random_state=2,
                           subsample=0.5)

In [124]:
clf.best_score_

0.6031746031746033

In [125]:
y_pred = cross_val_predict(clf.best_estimator_,X_test,y_test)
y_pred

C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [126]:
y_pred_clf = clf.best_estimator_.predict(X_test)

In [127]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y_test,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y_test,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y_test,y_pred_clf ,average='macro'))

precision =  0.6000000000000001
recall_score =  0.6190476190476191
f1_score 0.5833333333333333
