**pandas data frames**

In [112]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [113]:
read_data_file = pd.read_csv('project_hive.csv')

In [114]:
df = pd.DataFrame(read_data_file)

part of smell

In [115]:
commit_befor_sm = df.filter(regex='_befor')

In [116]:
commit_after_sm = df.filter(regex='_after')

In [117]:
group_befor_sm = df.filter(regex='_bf')

In [118]:
group_after_sm = df.filter(regex='_at')

In [119]:
#commit_after_sm.sum(axis=1)

In [120]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [121]:
commit_after = df['commit_after']

In [122]:
#commit_befor_sm.sum(axis=1)

In [123]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [124]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [125]:
commit_befor = df['commit_befor']

In [126]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [127]:
cal_smell =  df['cal_smell']

columns list

In [128]:
#list(df.columns)

In [129]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before' , 's2093_before']] 

In [130]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after' , 's2093_after']] 

In [131]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before' , 's2986_before' , 's3358_before' ,
            's135_before' , 's1117_before' , 's1197_before' , 's1104_before']] 

In [132]:
#'s135_after' ,'s1612_after' ,

In [133]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' , 's2986_after' , 's3358_after' ,
            's135_after' , 's1117_after' , 's1197_after' , 's1104_after']] 

In [134]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' , 
            's1066_before']] 

In [135]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            's1066_after']] 

In [136]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [137]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [138]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [139]:
data_time = df[{'open_time' , 'closed_time' }]

In [140]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [141]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [142]:
cal_time = df['cla_time']

In [143]:
cal_time.median()

Timedelta('27 days 03:41:00')

Information issus on GitHub 

In [144]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [145]:
changed_file = df['changed_file']

In [146]:
additions = df['additions']

In [147]:
deletions = df['deletions']

In [148]:
Dev = df['Dev']

data frame containing information 

In [149]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev ,
                              
                            })

In [150]:
data_flink

commit_befor   commit_after  cal_smell  dispen_bf  object_bf  bloater_bf  \
0            12.0           1.0      -11.0        0.0        0.0         3.0   
1             3.0           3.0        0.0        0.0        1.0         2.0   
2             3.0           0.0       -3.0        1.0        2.0         0.0   
3            29.0           3.0      -26.0        3.0        2.0        22.0   
4            26.0           2.0      -24.0        0.0        0.0        26.0   
5             7.0           1.0       -6.0        5.0        1.0         1.0   
6             4.0           0.0       -4.0        0.0        4.0         0.0   
7            14.0           0.0      -14.0        0.0        1.0        13.0   
8             2.0           1.0       -1.0        0.0        1.0         1.0   
9             0.0           0.0        0.0        0.0        0.0         0.0   
10            0.0           0.0        0.0        0.0        0.0         0.0   
11            0.0           0.0        0.0        0.0        0.0         0.0   

    dispen_at  object_at  bloater_af           open_time         closed_time  \
0         0.0        0.0         1.0 2017-02-02 20:03:00 2017-05-03 20:43:00   
1         3.0        0.0         0.0 2010-01-27 21:12:00 2011-12-17 00:03:00   
2         0.0        0.0         0.0 2010-05-19 01:43:00 2011-12-17 00:03:00   
3         0.0        0.0         0.0 2010-01-21 05:57:00 2010-01-21 14:29:00   
4         0.0        0.0         1.0 2009-08-24 17:40:00 2009-09-01 21:42:00   
5         1.0        0.0         0.0 2016-04-22 02:46:00 2016-10-25 03:43:00   
6         0.0        0.0         0.0 2013-03-12 00:48:00 2013-03-13 18:24:00   
7         0.0        0.0         0.0 2016-06-29 11:14:00 2016-07-26 14:55:00   
8         1.0        0.0         0.0 2016-12-03 04:32:00 2016-12-07 23:20:00   
9         0.0        0.0         0.0                 NaT                 NaT   
10        0.0        0.0         0.0                 NaT                 NaT   
11        0.0        0.0         0.0                 NaT                 NaT   

            cal_time  changed_file  additions  deletions  dev  
0   90 days 00:40:00          25.0     2277.0      153.0  1.0  
1  688 days 02:51:00          92.0     1014.0     1024.0  1.0  
2  576 days 22:20:00           6.0      187.0       39.0  2.0  
3    0 days 08:32:00          74.0     7475.0     5180.0  1.0  
4    8 days 04:02:00          63.0     2447.0     2225.0  1.0  
5  186 days 00:57:00           3.0      475.0       60.0  1.0  
6    1 days 17:36:00          40.0     7184.0        0.0  2.0  
7   27 days 03:41:00          11.0      266.0       37.0  2.0  
8    4 days 18:48:00           7.0      112.0       25.0  1.0  
9                NaT           NaN        NaN        NaN  NaN  
10               NaT           NaN        NaN        NaN  NaN  
11               NaT           NaN        NaN        NaN  NaN

In [151]:
from datetime import timedelta

In [152]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [153]:
data_flink['cal_time'].min()

Timedelta('0 days 08:32:00')

In [154]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x > timedelta (days = 27) else 1)

In [155]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [156]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [157]:
df_drop_nan = data_flink.dropna()

In [158]:
from sklearn.datasets import load_wine
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np

In [159]:
X ,y = df_drop_nan.iloc[:, [ True , False,  False , True , True ,True , False , False , False ,True , False , False, False , False , False , False,False]] , df_drop_nan['cal_time_binaly']

In [160]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import RidgeClassifierCV
X, y = load_breast_cancer(return_X_y=True)
clf = RidgeClassifierCV(alphas=[1e-3, 1e-2, 1e-1, 1]).fit(X, y)

In [161]:
from sklearn.model_selection import cross_val_score

In [162]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.95614035, 0.95614035, 0.93859649, 0.96491228, 0.97345133])

In [163]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [164]:
from sklearn.metrics import confusion_matrix

In [165]:
confusion_matrix(y , y_pred)

array([[189,  23],
       [  1, 356]], dtype=int64)

In [166]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred ))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred ))

precision =  0.9393139841688655
recall_score =  0.9971988795518207
f1_score 0.9673913043478262
