**pandas data frames**

In [1]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [2]:
read_data_file = pd.read_csv('..\project_flink.csv')

In [3]:
df = pd.DataFrame(read_data_file)

part of smell

In [4]:
commit_befor_sm = df.filter(regex='_befor')

In [5]:
commit_after_sm = df.filter(regex='_after')

In [6]:
group_befor_sm = df.filter(regex='_bf')

In [7]:
group_after_sm = df.filter(regex='_at')

In [8]:
#commit_after_sm.sum(axis=1)

In [9]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [10]:
commit_after = df['commit_after']

In [11]:
#commit_befor_sm.sum(axis=1)

In [12]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [13]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [14]:
commit_befor = df['commit_befor']

In [15]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [16]:
cal_smell =  df['cal_smell']

columns list

In [17]:
list(df.columns)

['url',
 'commit',
 'parents',
 's106_before',
 's106_after',
 's112_before',
 's112_after',
 's119_before',
 's119_after',
 's1123_before',
 's1123_after',
 's1133_before',
 's1133_after',
 's1141_before',
 's1141_after',
 's1155_before',
 's1155_after',
 's1168_before',
 's1168_after',
 's1172_before',
 's1172_after',
 's1181_before',
 's1181_after',
 's1187_before',
 's1187_after',
 's1192_before',
 's1192_after',
 's1199_before',
 's1199_after',
 's1610_before',
 's1610_after',
 's1612_before',
 'S1612_after',
 's1643_before',
 's1643_after',
 's1874_before',
 's1874_after',
 's1948_before',
 's1948_after',
 's1199_before.1',
 's1199_after.1',
 's2139_before',
 's2139_after',
 's2699_before',
 's2699_after',
 's2293_before',
 's2293_after',
 's3011_before',
 's3011_after',
 's3400_before',
 's3400_after',
 's3415_before',
 's3415_after',
 's3358_before',
 's3358_after',
 's3740_before',
 's3740_after',
 's3776_before',
 's3776_after',
 's4042_before',
 's4042_after',
 's5411_before

In [18]:
rule1_bf = df[['s6212_before' , 's1874_before' , 's1133_before' , 's1123_before' , 
            's1192_before' , 's106_before' , 's1155_before' , 's5411_before' ,
            's1172_before' , 's1141_before'  
             ]] 

In [19]:
rule1_at = df[['s6212_after' , 's1874_after' , 's1133_after' , 's1123_after' , 
            's1192_after' , 's106_after' , 's1155_after' , 's5411_after' ,
            's1172_after' , 's1141_after'  ]]

In [20]:
rule2_bf = df[['s119_before' , 's112_before' , 's3740_before' , 's1948_before' , 
            's1181_before' , 's5993_before' , 's3011_before' , 's1612_before' ,
            's2139_before' , 's1610_before'  , 's3358_before' ,
             ]] 

In [21]:
rule2_at = df[['s119_after' , 's112_after' , 's3740_after' , 's1948_after' , 
            's1181_after' , 's5993_after' , 's3011_after' , 's6212_after',
            's2139_after' , 's1610_after' ,  's3358_after' ,
            
            ]] 

In [22]:
rule3_bf = df[['s2293_before' , 's3776_before' , 's1199_before' , 's3358_before' ]] 

In [23]:
rule3_at = df[['s2293_after' , 's3776_after' , 's1199_after' , 's3358_after' , 
            ]] 

In [24]:
df['dispen_bf'] = rule1_bf.sum(axis=1)
df['object_bf'] = rule2_bf.sum(axis=1)
df['bloater_bf'] = rule3_bf.sum(axis=1)

In [25]:
df['dispen_at'] = rule1_at.sum(axis=1)
df['object_at'] = rule2_at.sum(axis=1)
df['bloater_at'] = rule3_at.sum(axis=1)

In [26]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

Set data type time  

In [27]:
data_time = df[{'open_time' , 'closed_time' }]

In [28]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [29]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [30]:
cal_time = df['cla_time']

In [31]:
cal_time.median()

Timedelta('17 days 02:22:30')

Information issus on GitHub 

In [32]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [33]:
changed_file = df['changed_file']

In [34]:
additions = df['additions']

In [35]:
deletions = df['deletions']

In [36]:
Dev = df['Dev']

data frame containing information 

In [37]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev 
                            })

In [38]:
from datetime import timedelta

In [39]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [40]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x < timedelta (days = 17) else 1)

In [41]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [42]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [43]:
df_drop_nan = data_flink.dropna()

In [44]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [45]:
X ,y = df_drop_nan.iloc[:, [ True , False,  False , True , True ,True , False , False , False ,True , False , False, False , False , False , False,False]] , df_drop_nan['cal_time_binaly']

In [46]:
X

commit_befor   dispen_bf  object_bf  bloater_bf  open_time
0               9          2          6           0          9
1              11          1          8           0          2
2               9          0          7           0          9
3              18          3          4           0          3
4               4          0          2           0          7
5              12          0         10           0          8
6               3          0          0           0          4
7               7          0          0           0         12
8               6          0          0           0          2
9               3          0          0           0         11
10             11          3          6           0          6
11             12          6          5           0          4
12             22         14          4           0         11
13              1          0          0           0          6
14              7          3          0           0          9
15             12         10          0           0         12
16             29         16          0          10         11
17              1          0          0           0          8
18              2          1          0           0         11
19             44         41          2           1          1
20             12         10          0           0          9
21              2          0          0           0         11
22              6          2          0           0          3
23             10          1          5           2          8
24              7          0          2           0          6
25              2          0          0           0          6
26              8          4          1           0          9
27              8          7          0           0          7
28             12          4          7           0          9
29             24          4          5          14         11

In [47]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [48]:
from sklearn.model_selection import cross_val_score

In [49]:
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.5       , 0.33333333, 0.33333333, 0.16666667, 0.66666667])

In [50]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(y,y_pred)

array([[ 8,  7],
       [11,  4]], dtype=int64)

In [53]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.36363636363636365
recall_score =  0.26666666666666666
f1_score 0.30769230769230765


In [54]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         15
y_pred    11
dtype: int64

In [55]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'degree': [1,2,4,8],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'degree': [1, 2, 4, 8],
                         'gamma': ['scale', 'auto'], 'random_state': [2]},
             scoring='f1_macro')

In [56]:
clf.best_estimator_

SVC(C=0.01, degree=1, gamma='auto', random_state=2)

In [57]:
clf.best_score_

0.452014652014652

In [58]:
y_pred_clf = clf.best_estimator_.predict(X)

In [59]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.96875
recall_score =  0.9666666666666667
f1_score 0.9666295884315907


In [63]:
frame={"y":y,"y_pred": y_pred_clf}
pd.DataFrame(frame)

y  y_pred
0   1       1
1   1       1
2   1       1
3   0       0
4   0       0
5   0       0
6   1       1
7   0       0
8   0       0
9   0       0
10  0       0
11  0       0
12  0       0
13  1       1
14  0       0
15  1       1
16  1       1
17  0       0
18  0       0
19  1       1
20  0       0
21  1       0
22  1       1
23  1       1
24  0       0
25  1       1
26  1       1
27  1       1
28  0       0
29  1       1

In [64]:
X

commit_befor   dispen_bf  object_bf  bloater_bf  open_time
0               9          2          6           0          9
1              11          1          8           0          2
2               9          0          7           0          9
3              18          3          4           0          3
4               4          0          2           0          7
5              12          0         10           0          8
6               3          0          0           0          4
7               7          0          0           0         12
8               6          0          0           0          2
9               3          0          0           0         11
10             11          3          6           0          6
11             12          6          5           0          4
12             22         14          4           0         11
13              1          0          0           0          6
14              7          3          0           0          9
15             12         10          0           0         12
16             29         16          0          10         11
17              1          0          0           0          8
18              2          1          0           0         11
19             44         41          2           1          1
20             12         10          0           0          9
21              2          0          0           0         11
22              6          2          0           0          3
23             10          1          5           2          8
24              7          0          2           0          6
25              2          0          0           0          6
26              8          4          1           0          9
27              8          7          0           0          7
28             12          4          7           0          9
29             24          4          5          14         11