**pandas data frames**

In [1]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

read file csv

In [2]:
read_data_file = pd.read_csv('type_smells.csv')

In [3]:
df = pd.DataFrame(read_data_file)

In [4]:
dispen_bf = df['dispen_bf']
object_bf = df['object_bf']
bloater_bf = df['bloater_bf']

In [5]:
dispen_at = df['dispen_at']
object_at = df['object_at']
bloater_at = df['bloater_at']

part of smell

In [6]:
commit_befor_sm = df.filter(regex='_befor')

In [7]:
commit_after_sm = df.filter(regex='_after')

In [8]:
group_befor_sm = df.filter(regex='_bf')

In [9]:
group_after_sm = df.filter(regex='_at')

In [10]:
commit_after_sm.sum(axis=1)

0      6
1     12
2      9
3      5
4      7
5      2
6     18
7      4
8      2
9      4
10     4
11     2
12     1
13    26
14     7
15    14
16    21
17     2
18    11
19    32
20     3
21    12
22    10
23     6
24     7
25    12
26     4
27     2
28     1
29     5
dtype: int64

In [11]:
df['commit_after'] = commit_after_sm.sum(axis=1)

In [12]:
commit_after = df['commit_after']

In [13]:
commit_befor_sm.sum(axis=1)

0      9
1     11
2      9
3     18
4      4
5     12
6      3
7      7
8      6
9      3
10    11
11    12
12    22
13     1
14     7
15    12
16    29
17     1
18     2
19    44
20    12
21     2
22     6
23    10
24     7
25     2
26     8
27     8
28    12
29    24
dtype: int64

In [14]:
df['commit_befor'] = commit_befor_sm.sum(axis=1)

In [15]:
commit_befor = df['commit_befor']

In [16]:
df['cal_smell']  = commit_after_sm.sum(axis=1) - commit_befor_sm.sum(axis=1)

In [17]:
cal_smell =  df['cal_smell']

columns list

In [18]:
list(df.columns)

['url',
 'commit',
 'parents',
 's106_before',
 's106_after',
 's112_before',
 's112_after',
 's119_before',
 's119_after',
 's1123_before',
 's1123_after',
 's1133_before',
 's1133_after',
 's1141_before',
 's1141_after',
 's1155_before',
 's1155_after',
 's1168_before',
 's1168_after',
 's1172_before',
 's1172_after',
 's1181_before',
 's1181_after',
 's1187_before',
 's1187_after',
 's1192_before',
 's1192_after',
 's1199_before',
 's1199_after',
 's1610_before',
 's1610_after',
 's1612_before',
 'S1612_after',
 's1643_before',
 's1643_after',
 's1874_before',
 's1874_after',
 's1948_before',
 's1948_after',
 's1199_before.1',
 's1199_after.1',
 's2139_before',
 's2139_after',
 's2699_before',
 's2699_after',
 's2293_before',
 's2293_after',
 's3011_before',
 's3011_after',
 's3400_before',
 's3400_after',
 's3415_before',
 's3415_after',
 's3358_before',
 's3358_after',
 's3740_before',
 's3740_after',
 's3776_before',
 's3776_after',
 's4042_before',
 's4042_after',
 's5411_before

In [19]:
rule  = df[{
     's106_before',
 's106_after',
 's112_before',
 's112_after',
 's119_before',
 's119_after',
 's1123_before',
 's1123_after',
 's1133_before',
 's1133_after',
 's1141_before',
 's1141_after',
 's1155_before',
 's1155_after',
 's1168_before',
 's1168_after',
 's1172_before',
 's1172_after',
 's1181_before',
 's1181_after',
 's1187_before',
 's1187_after',
 's1192_before',
 's1192_after',
 's1199_before',
 's1199_after',
 's1610_before',
 's1610_after',
 's1612_before',
 'S1612_after',
 's1643_before',
 's1643_after',
 's1874_before',
 's1874_after',
 's1948_before',
 's1948_after',
 's1199_before.1',
 's1199_after.1',
 's2139_before',
 's2139_after',
 's2699_before',
 's2699_after',
 's2293_before',
 's2293_after',
 's3011_before',
 's3011_after',
 's3400_before',
 's3400_after',
 's3415_before',
 's3415_after',
 's3358_before',
 's3358_after',
 's3740_before',
 's3740_after',
 's3776_before',
 's3776_after',
 's4042_before',
 's4042_after',
 's5411_before',
 's5411_after',
 's5777_before',
 's5777_after',
 's5993_before',
 's5993_after',
 's6212_before',
 's6212_after',
 's6213_before',
 's6213_after'
}]

Set data type time  

In [20]:
data_time = df[{'open_time' , 'closed_time' }]

In [21]:
open_time = pd.to_datetime(df['open_time'])
closed_time = pd.to_datetime(df['closed_time'])

In [22]:
df['cla_time'] = pd.to_datetime(df['closed_time']) - pd.to_datetime(df['open_time'])

In [23]:
cal_time = df['cla_time']

In [24]:
cal_time.median()

Timedelta('17 days 02:22:30')

Information issus on GitHub 

In [25]:
data_file = df[{'changed_file' , 'additions'  , 'deletions' , 'Dev' }]

In [26]:
changed_file = df['changed_file']

In [27]:
additions = df['additions']

In [28]:
deletions = df['deletions']

In [29]:
Dev = df['Dev']

data frame containing information 

In [30]:
data_flink = pd.DataFrame({  'commit_befor ' : commit_befor , 'commit_after' : commit_after, 'cal_smell' : cal_smell , 
                              'dispen_bf' :dispen_bf , 'object_bf' : object_bf , 'bloater_bf':bloater_bf ,
                              'dispen_at' :dispen_at , 'object_at' : object_at , 'bloater_af': bloater_at ,
                              'open_time' : open_time , 'closed_time' : closed_time , 'cal_time' : cal_time,
                              'changed_file' : changed_file , 'additions' : additions , 'deletions': deletions , 'dev': Dev ,
                              
                            })

In [31]:
from datetime import timedelta

In [32]:
data_flink[data_flink['cal_time'] < timedelta (minutes = 0)]

Empty DataFrame
Columns: [commit_befor , commit_after, cal_smell, dispen_bf, object_bf, bloater_bf, dispen_at, object_at, bloater_af, open_time, closed_time, cal_time, changed_file, additions, deletions, dev]
Index: []

In [33]:
data_flink['cal_time_binaly'] = data_flink['cal_time'].apply(lambda x:  0 if x > timedelta (days = 17) else 1)

In [34]:
data_flink['open_time'] = pd.DatetimeIndex(data_flink['open_time']).month

In [35]:
data_flink['closed_time'] = pd.DatetimeIndex(data_flink['closed_time']).month

Model

In [36]:
df_drop_nan = data_flink.dropna()

In [37]:
from sklearn.datasets import load_wine
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np

In [38]:
X ,y = df_drop_nan.iloc[:, [ True , False,  False , True , True ,True , False , False , False ,True , False , False, False , False , False , False,False]] , df_drop_nan['cal_time_binaly']

In [39]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [40]:
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(clf , X , y , cv=5 ,scoring= "accuracy")

array([0.5       , 0.5       , 0.33333333, 0.5       , 0.2       ])

In [42]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=3)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [43]:
confusion_matrix(y, y_pred)

array([[ 2, 12],
       [ 3, 12]], dtype=int64)

In [44]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.5
recall_score =  0.8
f1_score 0.6153846153846154
