In [1]:
from sklearn.datasets import load_wine
from datetime import timedelta
import pandas as pd
import numpy as np

In [2]:
read_data_file = pd.read_csv('..\dataFrame_hive.csv')
df = pd.DataFrame(read_data_file)

In [3]:
X = df[['commit_befor ', 'dispen_bf', 'object_bf', 'bloater_bf', 'open_time',]]
y = df['cal_time_binaly']

In [4]:
X_train ,X_test ,y_train , y_test = X[:20], X[20:],y[:20],y[20:]

In [5]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [6]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.5       , 0.5       , 0.33333333, 0.5       , 0.66666667])

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [8]:
y_pred_test =cross_val_predict(clf,X_test,y_test,cv=5)
y_pred_test

C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [9]:
confusion_matrix(y,y_pred)

array([[12,  4],
       [11,  3]], dtype=int64)

In [10]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.42857142857142855
recall_score =  0.21428571428571427
f1_score 0.2857142857142857


In [11]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         14
y_pred     7
dtype: int64

In [12]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X_test,y_test)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'gamma': ['scale', 'auto'],
                         'random_state': [2]},
             scoring='f1_macro')

In [13]:
y_pred_clf = clf.best_estimator_.predict(X)
y_pred_clf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.7857142857142857
recall_score =  0.5714285714285714
f1_score 0.48863636363636365
