In [35]:
from sklearn.datasets import load_wine
from datetime import timedelta
import pandas as pd
import numpy as np

In [36]:
read_data_file = pd.read_pickle('../hive.pkl')
df = pd.DataFrame(read_data_file)

In [37]:
#X = df[['commit_befor ', 'dispen_bf', 'object_bf', 'bloater_bf', 'open_time',]]
X = df[[ 'dispen_bf', 'object_bf', 'bloater_bf', ]]
y = df['cal_time_binaly']

In [38]:
X_train ,X_test ,y_train , y_test = X[:20], X[20:],y[:20],y[20:]

In [39]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [40]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.66666667, 0.33333333, 0.33333333, 0.5       , 0.66666667])

In [41]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1], dtype=int64)

In [42]:
y_pred_test =cross_val_predict(clf,X_test,y_test,cv=5)
y_pred_test

C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
confusion_matrix(y,y_pred)

array([[ 3, 11],
       [ 4, 12]], dtype=int64)

In [44]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.5217391304347826
recall_score =  0.75
f1_score 0.6153846153846153


In [45]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         16
y_pred    23
dtype: int64

In [46]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X_test,y_test)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'gamma': ['scale', 'auto'],
                         'random_state': [2]},
             scoring='f1_macro')

In [47]:
y_pred_clf = clf.best_estimator_.predict(X)
y_pred_clf

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [48]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.7857142857142857
recall_score =  0.5714285714285714
f1_score 0.48863636363636365


In [53]:
from matplotlib import pyplot as plt
from sklearn import svm
import numpy as np

def f_importances(coef, names):
    
    names = np.arange(1)
    imp = coef
    imp,names = zip(*sorted(zip(imp,names)))
    plt.barh(range(len(names)), imp, align='center')
    plt.yticks(range(len(names)), names)
    plt.show()

features_names = X.columns
svm1 = svm.SVC(kernel='linear',C=1)
svm1.fit(X_test, y_test)

SVC(C=1, kernel='linear')

In [54]:
svm1.coef_

array([[-0.93371166,  0.        , -0.03223859]])

In [55]:
import itertools
from itertools import product 

In [56]:
result = itertools.combinations(X ,2)

for item in result:
    df  = pd.DataFrame(item)
    X[list (item)]
    parameters = {
    'C': [0.01 , 0.1 ,1],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
    }
    svc = SVC()
    clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
    clf.fit(X_train[list (item)],y_train)
    clf.predict(X_test[list (item)])
    #print('predict=',clf.predict(X_test[list (item)]))
    #print(X_test)
    #print("y_train = ",y_train)
    print(item)
    print("precision_score =",precision_score(clf.predict(X[list(item)]),y))
    print("recall_score =", recall_score(clf.predict(X[list(item)]),y))
    print("f_1=",f1_score(clf.predict(X[list(item)]),y,average='macro'))
    #print("f_1_X-test=",f1_score(clf.predict(X_test[list(item)]),y_test,average='macro'))
    

('dispen_bf', 'object_bf')
precision_score = 0.0
recall_score = 0.0
f_1= 0.3181818181818182
('dispen_bf', 'bloater_bf')
precision_score = 0.6875
recall_score = 0.6470588235294118
f_1= 0.6296296296296298


C:\Users\Beauz\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


('object_bf', 'bloater_bf')
precision_score = 0.375
recall_score = 0.6666666666666666
f_1= 0.5542857142857143
