In [559]:
from sklearn.datasets import load_wine
from datetime import timedelta
import pandas as pd
import numpy as np

In [560]:
read_data_file = pd.read_csv('..\dataFrame_flink.csv')
df = pd.DataFrame(read_data_file)

In [561]:
df.columns

Index(['commit_befor ', 'commit_after', 'cal_smell', 'dispen_bf', 'object_bf',
       'bloater_bf', 'dispen_at', 'object_at', 'bloater_af', 'open_time',
       'closed_time', 'cal_time', 'changed_file', 'additions', 'deletions',
       'dev', 'cal_time_binaly'],
      dtype='object')

In [562]:
X = df[['commit_befor ', 'dispen_bf', 'object_bf', 'bloater_bf', 'open_time',]]
y = df['cal_time_binaly']

In [563]:
X = X.dropna()
y = y.dropna()

In [564]:
X_train ,X_test ,y_train , y_test = X[:20], X[20:],y[:20],y[20:]

In [565]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [566]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf , X , y , cv=5 , scoring= "accuracy")

array([0.5       , 0.33333333, 0.33333333, 0.16666667, 0.66666667])

In [567]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf,X,y,cv=5)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [568]:
confusion_matrix(y,y_pred)

array([[ 8,  7],
       [11,  4]], dtype=int64)

In [569]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred))
print('recall_score = ', recall_score(y,y_pred))
print('f1_score',f1_score(y,y_pred))

precision =  0.36363636363636365
recall_score =  0.26666666666666666
f1_score 0.30769230769230765


In [570]:
frame={"y":y,"y_pred": y_pred}
pd.DataFrame(frame).sum()

y         15
y_pred    11
dtype: int64

In [589]:
from sklearn.model_selection import GridSearchCV

parameters = {
  
    'C': [0.01 , 0.1 ,1],
    'gamma' : ['scale' , 'auto'],
    'random_state':[2]
  
}
svc = SVC()
clf = GridSearchCV(svc , parameters , cv=3 , scoring='f1_macro')
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1], 'gamma': ['scale', 'auto'],
                         'random_state': [2]},
             scoring='f1_macro')

In [590]:
clf.best_estimator_

SVC(C=0.01, gamma='auto', random_state=2)

In [591]:
y_pred = clf.predict(X)
y_pred

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [592]:
clf.predict(X_test)

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [575]:
clf.best_estimator_

SVC(C=0.01, random_state=2)

In [593]:
y_pred_clf = clf.best_estimator_.predict(X)
y_pred_clf

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1], dtype=int64)

In [594]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('precision = ', precision_score(y,y_pred_clf ,average='macro'))
print('recall_score = ', recall_score(y,y_pred_clf ,average='macro'))
print('f1_score',f1_score(y,y_pred_clf ,average='macro'))

precision =  0.96875
recall_score =  0.9666666666666667
f1_score 0.9666295884315907


In [578]:
frame={"y":y,"y_pred_clf": y_pred_clf}
pd.DataFrame(frame)

y  y_pred_clf
0   1           1
1   1           1
2   1           1
3   0           1
4   0           1
5   0           1
6   1           1
7   0           1
8   0           1
9   0           1
10  0           1
11  0           1
12  0           1
13  1           1
14  0           1
15  1           1
16  1           1
17  0           1
18  0           1
19  1           1
20  0           1
21  1           1
22  1           1
23  1           1
24  0           1
25  1           1
26  1           1
27  1           1
28  0           1
29  1           1

In [579]:
from matplotlib import pyplot as plt
from sklearn import svm
import numpy as np

def f_importances(coef, names):
    
    names = np.arange(1)
    imp = coef
    imp,names = zip(*sorted(zip(imp,names)))
    plt.barh(range(len(names)), imp, align='center')
    plt.yticks(range(len(names)), names)
    plt.show()

features_names = X.columns
svm1 = svm.SVC(kernel='linear',C=1)
svm1.fit(X, y)

SVC(C=1, kernel='linear')

In [580]:
svm1.coef_

array([[-0.50518342,  0.48324321,  0.36899649,  1.17543127, -0.28573192]])

In [581]:
import itertools
from itertools import product 

In [598]:
result = itertools.combinations(X ,2)

for item in result:
    df  = pd.DataFrame(item)
    print(item)

('commit_befor ', 'dispen_bf')
('commit_befor ', 'object_bf')
('commit_befor ', 'bloater_bf')
('commit_befor ', 'open_time')
('dispen_bf', 'object_bf')
('dispen_bf', 'bloater_bf')
('dispen_bf', 'open_time')
('object_bf', 'bloater_bf')
('object_bf', 'open_time')
('bloater_bf', 'open_time')


In [599]:
itertools.combinations_with_replacement(X,2)

In [602]:
l = list(itertools.combinations_with_replacement(X,2))
print(l)

[('commit_befor ', 'commit_befor '), ('commit_befor ', 'dispen_bf'), ('commit_befor ', 'object_bf'), ('commit_befor ', 'bloater_bf'), ('commit_befor ', 'open_time'), ('dispen_bf', 'dispen_bf'), ('dispen_bf', 'object_bf'), ('dispen_bf', 'bloater_bf'), ('dispen_bf', 'open_time'), ('object_bf', 'object_bf'), ('object_bf', 'bloater_bf'), ('object_bf', 'open_time'), ('bloater_bf', 'bloater_bf'), ('bloater_bf', 'open_time'), ('open_time', 'open_time')]


In [583]:
def combinations(iterable, r):
    pool = tuple(iterable)
    n = len(pool)
    for indices in permutations(range(n), r):
        if sorted(indices) == list(indices):
            yield tuple(pool[i] for i in indices)
    print(permutations)

In [614]:
def FunctionName( X ):
    loop = tuple(X)
    n= len(loop)
    for col in itertools.combinations_with_replacement(n,r=2):
        if col == list(col):
            return (loop[i] for i in col)
        
        print(n)

In [612]:
print(FunctionName)

<function FunctionName at 0x0000020DAAA6A430>


In [584]:
print(combinations)

<function combinations at 0x0000020DAAABAE50>


In [585]:
print([''.join(i) for i in itertools.combinations(pd.DataFrame(X), 2)])

['commit_befor dispen_bf', 'commit_befor object_bf', 'commit_befor bloater_bf', 'commit_befor open_time', 'dispen_bfobject_bf', 'dispen_bfbloater_bf', 'dispen_bfopen_time', 'object_bfbloater_bf', 'object_bfopen_time', 'bloater_bfopen_time']


In [586]:
def random_combination(iterable, r):
       "Random selection from itertools.combinations(iterable, r)"
       pool = tuple(iterable)
       n = len(pool)
       indices = sorted(random.sample(range(n), r))
       return tuple(pool[i] for i in indices)

In [587]:
print(random_combination)

<function random_combination at 0x0000020DAAABACA0>
